### ISSUE TITLE
Удаление трека из библиотеки.

### ISSUE THREAD

**Issue by ForeshadowRU** [JesperRU/java-music-player#18]
При клике на трек, нужно выводить контекстное меню с возможностью удалить трек.
[Guilde по MenuItem](http://o7planning.org/ru/11115/javafx-contextmenu-tutorial). Ну и естественно пересчитывать layoutY для всех не удалённых.

В последствии добавить возможность удалить все выделенные треки из библиотеки.

**Comment by kreeper55** [comment]
I did half the work
